package o;

/* loaded from: C:\Users\User\Downloads\PREM space\dex2jar-2.0\andro259\classes.dex */
public enum my {
    iRO_hockeyapp,
    iRO_googleplay,
    MOTR,
    XileRO,
    AevaRO,
    FreeRO,
    MyRO,
    ChenRO,
    WeDevGames,
    ROProviderValkyrie,
    AtlasRO,
    TheClassicROCom,
    ClassicRONet,
    InfamyRO,
    PlayragnarokPh,
    SarahServer,
    SuccessRoNet,
    CrownRO,
    Eden3,
    Class2RO,
    ShinServer,
    EosRagnarokOnline,
    TyrServer,
    MobiRO,
    PlayLokiServerCom,
    FreeRoWeb,
    OldchaosROCom,
    Gugusjungs57572,
    LidiaRO,
    RagnarevivalCom,
    RebirthRO_Ancyker,
    BarnabyRO,
    Ragnaclan,
    ThaiRoInTh,
    LeonardRO,
    IfritRagnarokCom,
    AmatsuRO,
    FreePlayRoCom,
    RoHeimdallCom,
    Thai_id9169,
    localclient,
    PlayvalhallaPh,
    Classic2RoInTh,
    Daro,
    iPlayRo201804,
    AustinRO,
    BrightRO,
    TitanRO,
    RoFaction,
    WeloveRo,
    KafraRO,
    ChaosReborn,
    RagnarokReturnPh,
    GachoRO,
    RoRetro,
    LibRO,
    SecretRO,
    NorseRO,
    Trinity_Reborn_Full,
    AlbertaServer,
    hiclassro,
    OldschoolragnarokCom,
    Ragnarevo,
    CrazyPoring,
    LucianoRO,
    GarciaRO,
    Blytanias,
    PinoyRO,
    OMGRO,
    RagnarokPuzzle,
    Modify_Full,
    Newyear,
    GRANDRO,
    SakrayPh,
    MyRebornRO,
    XileRO2019,
    eSport2019,
    PhoenixRO2,
    OcrClassicCom,
    RoFreedom,
    C2RO,
    RelaxRO,
    BgRO,
    ROClashed,
    ForceRO,
    KryptGamingClassic,
    OSRO2019,
    NewFenrirRoGameNet,
    RagnarokIsLife,
    LevelRO,
    OfficialragnarokCom,
    PayonRO,
    OsirisRO,
    ROComfy,
    RoPronteraEp5,
    LeviathanRO,
    Ragnajapan,
    EarlyRO,
    BurnRO,
    PlayValhallaNet,
    DarkRO,
    EliteRO,
    BalikRagnaPH,
    SolaceRO,
    PhRoNet,
    MidgardRO,
    all;

    /* renamed from: values, reason: to resolve conflict with enum method */
    public static my[] valuesCustom() {
        my[] myVarArrValuesCustom = values();
        int length = myVarArrValuesCustom.length;
        my[] myVarArr = new my[length];
        System.arraycopy(myVarArrValuesCustom, 0, myVarArr, 0, length);
        return myVarArr;
    }
}
